name: Build APK

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build APK via Kivy Container
      uses: ArtemSuda/Action-Android-Buildozer@v1.3
      with:
        buildozer_version: 'stable'
        requirements: python3,kivy==2.3.0,asyncua
        permissions: INTERNET
        archs: arm64-v8a

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: OpcAgent-APK
        path: bin/*.apk
